### PR TITLE
feat(refacto): Move adobeFunctions.js to react component + Fix memory leak

### PR DESCRIPTION
**Pull request by gnuletik**
Hi @bibixx,

This PR introduces many changes.
- Delete adobeFunctions.js and move its code to the React Component
- This allows to fix a memory leak when inserting / deleting the component (with the removeEventListener calls)
- Replace deprecated react's `componentWillUpdate` with `componentDidUpdate`

Let me know if you have any question.
Thanks !

### CODE REVIEW

**Comment by bibixx** [comment]
Hey, thanks for contribution. I don't have much time right now but I'll take a look on it on monday. Cheers!

**Comment by bibixx** [comment]
Ok @gnuletik sorry for late response but I honestly didn't have time. I see the problem that it fixes, but could we maybe move all of Adobe functions back to the external file? Maybe create a class that would hold both.

**Comment by gnuletik** [comment]
Hi @bibixx, thanks for having a look!

I personally find it more clear to keep the `resizeCanvas`, `getComposition` and `initAdobeAn` functions inside the component file as we are interacting with the lib from the component anyway (with the `this.lib.tickEnabled` and `this.lib.visible`).

Also, keeping the DOM interaction inside the component file makes more sense according to the React's way of doing.

In fact, we could move some functions to a class instanciated for each animation but I don't really see the point here.

**Comment by bibixx** [comment]
Ok, I see it. So could you please rebase you PR with current master and make sure eslint doesn't throw any error? Because I have changed a few things recently

**Comment by gnuletik** [comment]
Thanks @bibixx!

I rebased from your last changes and eslint is okay:

```bash
react-adobe-animate ❯❯❯ yarn run lint
yarn run v1.15.2
$ eslint src/*
✨  Done in 1.77s.
```

**Comment by bibixx** [comment]
Great. I'll merge it in the evening then.

**Comment by bibixx** [comment]
@gnuletik Just fyi there where actually a few linting errors. But I have fixed them, and new version of package have just been published

**Comment by gnuletik** [comment]
Oh sorry for the linting errors, I may have missed something in my eslint config.
Thanks for the merge :)

**Pull request merged**
